# Generated by Django 3.2.16 on 2025-06-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_current_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='current_post',
            new_name='post',
        ),
    ]
